### ISSUE TITLE
有的车次查不到

### ISSUE THREAD

**Issue by kosmgco** [JingDa-open-source-community/go-home#1]
k9426 和 k9431的结果如下:
![image](https://cloud.githubusercontent.com/assets/23572982/22179467/c741d12c-e08f-11e6-9b11-d99cf302cba5.png)
12306官网的结果：
![image](https://cloud.githubusercontent.com/assets/23572982/22179481/4551ea52-e090-11e6-8ad4-0e91cbed6abb.png)

**Comment by liyu4** [comment]
谢谢你的issue，这个问题出现的原因是要指定日期，尤其是最近12306调整比较频繁，加入日期参数，以及其他调整我已经完，稍后就会更新。

**Comment by liyu4** [comment]
![](http://p1.bqimg.com/524586/5b4ee43ab0e16b3cs.jpg)
