### ISSUE TITLE
windows 上无法编译，包引入的路径貌似不对

### ISSUE THREAD

**Issue by CNMan** [JingDa-open-source-community/go-home#2]
```
>go get github.com/JingDa-open-source-community/go-home
package go-home/call: unrecognized import path "go-home/call" (import path does not begin with hostname)
```

```
E:\Backup\go\src\github.com\JingDa-open-source-community\go-home>go build
main.go:4:2: cannot find package "go-home/call" in any of:
        E:\dev\go\src\go-home\call (from $GOROOT)
        E:\Backup\go\src\go-home\call (from $GOPATH)
```

**Comment by CNMan** [comment]
https://github.com/JingDa-open-source-community/go-home/blob/master/main.go#L4
https://github.com/JingDa-open-source-community/go-home/blob/master/call/journey.go#L17
改成绝对路径编译完成。
```
github.com/JingDa-open-source-community/go-home/call
github.com/JingDa-open-source-community/go-home/util
```

但是cmd里的颜色控制符不起作用:(
![2017-01-26_133949](https://cloud.githubusercontent.com/assets/8692234/22321160/59496bda-e3cd-11e6-8118-1680fa2706a9.png)

**Comment by CNMan** [comment]
时刻表不能查询

```
>go-home train D322 2017-02-01
2017/01/26 13:45:15 open go-home.exe/util/compress.data: The system cannot find the path specified.
```

**Comment by liyu4** [comment]
在老家，无网络，明天一起商量

**Comment by liyu4** [comment]
1. 目前使用的路径是linux下的/，window需要以//作为分隔符。
2. window的序列化转译解释是微软自己搞的。支持需要做一些处理。

**Comment by liyu4** [comment]
路径改过来了，但是我没有window的环境，您要是方便就测试一下！

**Comment by liyu4** [comment]
应该已经支持window下的控制序列显示了！请测试一下！

**Comment by CNMan** [comment]
路径还是不行
```
E:\Backup\go\src\github.com\JingDa-open-source-community\go-home>go build
main.go:4:2: cannot find package "go-home/call" in any of:
        E:\dev\go\src\go-home\call (from $GOROOT)
        E:\Backup\go\src\go-home\call (from $GOPATH)

E:\Backup\go\src\github.com\JingDa-open-source-community\go-home>
```

**Comment by liyu4** [comment]
这是编译的路径，你试试go install

**Comment by liyu4** [comment]
这是编译的路径，你放在github下，肯定有包找不到，直接把go-home放在src下

**Comment by CNMan** [comment]
go get 默认是这样的路径

**Comment by liyu4** [comment]
恩 为了能看到效果  先git clone 到src下，然后go install

**Comment by CNMan** [comment]
![2017-02-07_144420](https://cloud.githubusercontent.com/assets/8692234/22680624/f5dac2ee-ed43-11e6-8de9-359496dad39f.png)
还是不行

**Comment by liyu4** [comment]
恩，只剩下转义字符的问题了，没办法我尝试了一次，但是还是不能被解决。待解决。 #bug

**Comment by liyu4** [comment]
![image](https://cloud.githubusercontent.com/assets/5621417/22770482/d0433564-eecb-11e6-9cf1-5612d1cb9fb1.png)

**Comment by liyu4** [comment]
bug已经解决了，改动较大，代码重新整理之后再上传。
