### ISSUE TITLE
查不到余票？

### ISSUE THREAD

**Issue by SoLaF** [JingDa-open-source-community/go-home#4]
可以查车次，但查余票打印的是空表：
![capture](https://cloud.githubusercontent.com/assets/26849436/26762561/05ad4478-4977-11e7-9548-bc18fd6f3595.GIF)

**Comment by liyu4** [comment]
是的，余票接口已经失效，因为12306的接口返回数据已经改变了，之前的解析方式不再适用，这个改起来需要一点时间。

**Comment by SoLaF** [comment]
哦哦，谢谢。这样子啊，铁道部怎么老改API。

**Comment by liyu4** [comment]
反爬

**Comment by SoLaF** [comment]
好想反反爬。请问这种接口怎么找啊，我试着看12306的URL请求，发现还是你写的这个呀，是什么变了？

**Comment by liyu4** [comment]
接口返回的数据变了，变的很难懂的一串
